name: Protocolo Nexus - Build Electron

on:
  repository_dispatch:
    types: [frontend-updated] # Se activa con la se√±al del repo WEB

jobs:
  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download Frontend from WEB Repo
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          workflow: main.yml # Debe coincidir con el nombre del archivo en el repo WEB
          name: frontend-dist
          repo: Grupo-2-DPM/DeepSaffix-WEB
          path: dist

      - name: Install & Build Electron
        run: |
          npm install
          npm run build  -- --publish always 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}